extends: "@istanbuljs/nyc-config-babel"
all: true
skip-full: false
exclude:
  - "lib/**/*.js"
  - "dist/**/*.js"
  - "scripts/**/*.js"
  - "coverage/**/*.js"
  - "src/test/clients/remote-tunneller.js"
  - "src/test/clients/waychaser-via-webdriver.js"
  - "src/test/clients/webdriver-*.js"
  - "src/util/abstract.js"
  - "src/test/siren-example.steps.js"
check-coverage: false
reporter:
  - text-summary
  - lcov
  - text
